name: Build packages with Termux
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Build package by ${{ github.actor }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Configuration
      run: |
        echo "ENABLE_NETHUNTER=$(cat $CONFIG_ENV | grep -w "ENABLE_NETHUNTER" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
        
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup build packages
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "DEVICE=$(echo ${{ env.KERNEL_CONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt update && sudo apt install tk-dev -y 
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/tomxi1997/dockerd2.git dockerd2
        git clone https://github.com/tomxi1997/termux-packages termux-packages
        cd termux-packages
        rm root-packages/containerd/too_long_path.patch
        sed -i 's/TERMUX_PKG_VERSION=1:/TERMUX_PKG_VERSION=/' ./root-packages/docker/build.sh
        sed -i 's/${TERMUX_PKG_VERSION:2}/${TERMUX_PKG_VERSION}/g' ./root-packages/docker/build.sh
        patch -p1 < $GITHUB_WORKSPACE/kernel_workspace/dockerd2/patches/cmd.patch
        
        ./scripts/run-docker.sh ./build-package.sh -i --format debian aria2 samba sftpgo zsync tdl 
        cd output
        mkdir out
        cp *.deb ./out
        tar -czvf out.tar.xz out
        cp out.tar.xz $GITHUB_WORKSPACE/kernel_workspace/
        
    - name: How many packages
      run: |
        echo "///////////////////////////////////////////"
        ls $GITHUB_WORKSPACE/kernel_workspace/termux-packages/output
        echo "///////////////////////////////////////////"

    - name: Upload package 
      uses: actions/upload-artifact@v4
      with:
        name: package-android24-arm64
        path: kernel_workspace/out.tar.xz